import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import logo from '../public/logo.png'
import { GiThorHammer } from 'react-icons/gi'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/tws.ico" />
      </Head>

      <main className={styles.main}>
        <Image
        src={logo}
        />

        <h1>TWS Soluções em Tecnologia</h1>

        <h2>Site em Contrução</h2>
        <GiThorHammer 
        size={70}
        />




      </main>

      <footer className={styles.footer}>
      <p> Oferecemos atendimento humanizado e personalizado.</p>
      
      
      </footer>
    </div>
  )
}

export default Home
